name: smartsnipping
description: A cross-platform screenshot and annotation tool for architecture.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # 状态管理
  provider: ^6.1.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  
  # UI 工具
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  
  # 编辑器相关
  # flutter_painter: ^1.0.1  # 旧版本，已替换为 flutter_painter_v2
  font_awesome_flutter: ^10.1.0  # 图标
  perfect_freehand: ^1.0.4  # 手绘优化
  flex_color_picker: ^3.7.1  # 颜色选择器
  popover: ^0.2.8  # 弹出控件
  
  # 功能性包
  image: ^4.0.17
  path_provider: ^2.0.15
  shared_preferences: ^2.2.2
  file_picker: ^10.1.2
  screenshot: ^2.1.0
  
  # 高级功能所需依赖
  desktop_window: ^0.4.0
  window_manager: ^0.4.3
  screen_capturer: ^0.2.3
  screen_retriever: ^0.2.0
  
  # 国际化
  intl: ^0.19.0
  
  # 工具类
  uuid: ^4.2.2
  equatable: ^2.0.5
  logger: ^2.5.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.8.3
  clipboard_watcher: ^0.3.0
  vector_math: ^2.1.4
  go_router: ^15.1.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  tray_manager: ^0.5.0
  file_saver: ^0.2.14
  flutter_painter_v2: ^2.1.0+1
  share_plus: ^11.0.0
  flutter_colorpicker: ^1.1.0
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # 在assets部分添加状态栏图标资源 